name: Python application - tests

on:
  # push:
  #   branches: [master]
  pull_request:
    branches: [master]

env:
  SG_CLIENT_ID: ${{ secrets.SG_CLIENT_ID }}
  SG_SECRET_KEY: ${{ secrets.SG_SECRET_KEY }}

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      # Download SourceGuard
      - name: Download SourceGuard
        run: |
          curl -o sourceguard-cli --location https://storage.googleapis.com/release-cli-prod/v0.0.106/linux/amd64/sourceguard-cli
          chmod u+x ./sourceguard-cli
      # Run sourceguard-cli
      - name: Run sourceguard-cli
        run: |
          ./sourceguard-cli -src ./
  # dummy run for docker release - only build, won't push as no tag
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cndino/cicd-demo
          tag_with_ref: true
          tags: latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
